# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hi! We've noticed that this is your first issue. Please be aware that when you would like to merge your changes, they must be approved by a member of the HaCS committee first. Thanks!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request! Please be aware that your changes must be approved by a member of the HaCS committee.

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! Thank you for helping to make the HaCS website better!

# It is recommend to include as many gifs and emojis as possible
